spring.application.name=main-app
server.port=${PORT_NUMBER:8080}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:1800000}

app.security.token.max-version=${MAX_TOKEN_VERSION:100000}
app.cors.allowed-origins=http://localhost:3001

# E-Mail Service
spring.mail.host=smtp.maileroo.com
spring.mail.port=2525
spring.mail.username=${SMTP_USER_NAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
app.email.sender=Eco App <NoReply@denis-kim.dev>

# Logging
logging.level.root=info
logging.level.eco.backend.main_app=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.org.hibernate.SQL=WARN
logging.file.name=logs/app-logs.log
logging.logback.rollingpolicy.file-name-pattern=logs/app-logs-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=15
logging.logback.rollingpolicy.total-size-cap=1GB

# Datenbank-Verbindung
spring.datasource.url=jdbc:sqlite:database/eco_app.db?foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC

# WICHTIG: Der korrekte Dialekt für Spring Boot 3+ / Hibernate 6
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Zeige SQL im Log
spring.jpa.show-sql=true
# Formatiert das SQL im Log lesbarer
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Erstellt Tabellen automatisch beim Start
spring.jpa.hibernate.ddl-auto=update

# Flyway aktivieren
spring.flyway.enabled=true
# Sagt Flyway, wo die Skripte liegen (Standard)
spring.flyway.locations=classpath:database/migration

# Placeholder für Flyway
# Syntax: spring.flyway.placeholders.[NAME_IM_SQL_FILE] = [${WERT}]
spring.flyway.placeholders.admin_name=${ADMIN_NAME}
spring.flyway.placeholders.admin_hash=${ADMIN_PASSWORD_HASH}
spring.flyway.placeholders.admin_tfa_code=${ADMIN_TFA_CODE}
spring.flyway.placeholders.test_user_name=${TEST_USER_NAME}
spring.flyway.placeholders.test_user_email=${TEST_USER_EMAIL}
spring.flyway.placeholders.test_user_hash=${TEST_USER_PASSWORD_HASH}
spring.flyway.placeholders.test_user_tfa_code=${TEST_USER_TFA_CODE}

# Fix für einen bekannten Bug bei SQLite Datumsfeldern in älteren Treibern
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.connection.date_string_format=yyyy-MM-dd HH:mm:ss

# Fehlermeldungen im Log anzeigen (DEBUGGING)
server.error.include-message=never
server.error.include-stacktrace=never
